(()=>{const d=document,n=d.querySelector('.nav');if(!n)return;const s=d.createElement('style');s.textContent='.nav{transition:height .55s cubic-bezier(.16,1,.3,1),background .55s,backdrop-filter .55s}.nav:not(.scrolled) nav{display:none!important}.nav .nav-toggle{display:block}.nav.scrolled{height:68px}.nav.scrolled .brand-logo{width:150px}.nav.scrolled .brand-wordmark{transform:scale(.9);transform-origin:left center}.am-menu-links{display:grid;grid-template-columns:1fr 1fr;gap:0 7vw}.am-menu-links a:nth-child(n){min-width:0}.am-menu-links a:nth-child(5){grid-column:1}.am-menu-links a:nth-child(13){grid-column:1 / -1;font-size:clamp(12px,1.2vw,16px);font-family:var(--sans);letter-spacing:.22em;color:var(--am-gold);padding-top:30px}.nav.scrolled nav{display:flex!important}.nav.scrolled nav>a,.nav.scrolled nav>details{display:none}.nav.scrolled nav>.nav-cta{display:inline-flex}.nav.scrolled nav>.nav-cta{margin-left:0}.nav.scrolled .nav-toggle{margin-left:18px}@media(max-width:1050px){.nav:not(.scrolled) nav,.nav.scrolled nav{display:none!important}.nav.scrolled{height:72px}.nav.scrolled .brand-logo{width:140px}.am-menu-links{grid-template-columns:1fr}}@media(prefers-reduced-motion:reduce){.nav{transition:none}.nav.scrolled .brand-wordmark{transform:none}}';d.head.appendChild(s);addEventListener('scroll',()=>n.classList.toggle('scrolled',scrollY>30),{passive:true});n.classList.toggle('scrolled',scrollY>30);})();
(()=>{const d=document,h=d.querySelector('.hero-home'),inner=h&&h.querySelector('.hero-inner');if(!h||!inner)return;const logo=d.createElement('img');logo.className='hero-brand';logo.src='assets/logo-master.svg';logo.alt='Andrzej Mikulski — MojeAlterego';logo.width=1600;logo.height=900;inner.insertBefore(logo,inner.firstChild);if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;let raf=0;h.addEventListener('pointermove',e=>{if(raf)return;raf=requestAnimationFrame(()=>{raf=0;const r=h.getBoundingClientRect(),x=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y=Math.max(0,Math.min(1,(e.clientY-r.top)/r.height));h.style.setProperty('--hero-light-x',`${x*100}%`);h.style.setProperty('--hero-light-y',`${y*100}%`);});},{passive:true});})();
(()=>{const d=document,r=d.documentElement,b=d.body;
const css=d.createElement('link');css.rel='stylesheet';css.href='absolute-maximum.css';d.head.appendChild(css);
const progress=d.createElement('div');progress.id='lux-progress';b.appendChild(progress);
const cursor=d.createElement('div');cursor.id='lux-cursor';b.appendChild(cursor);
const nav=d.querySelector('.nav'),toggle=d.querySelector('.nav-toggle');
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
if(toggle&&nav){toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));});}
const links=[...d.querySelectorAll('a[href]')].filter(a=>a.getAttribute('href')&&a.getAttribute('href')!=='#');
if(nav){const menu=d.createElement('div');menu.className='am-menu';menu.innerHTML='<div class="am-menu-links"></div><div class="am-meta"><strong>MOJEALTEREGO</strong><br>THE WORLD IS LARGER THAN THE PAGE.<br><br>⌘/CTRL K · SEARCH</div>';const list=menu.querySelector('.am-menu-links');const seen=new Set();links.forEach(a=>{const href=a.href;if(seen.has(href))return;seen.add(href);const x=d.createElement('a');x.href=a.getAttribute('href');x.textContent=a.textContent.trim();if(x.textContent)list.appendChild(x)});b.appendChild(menu);if(toggle)toggle.addEventListener('click',()=>menu.classList.toggle('open'));menu.addEventListener('click',e=>{if(e.target.tagName==='A')menu.classList.remove('open')});}
const io=new IntersectionObserver(es=>es.forEach(x=>{if(x.isIntersecting){x.target.classList.add('in');io.unobserve(x.target)}}),{threshold:.08,rootMargin:'0px 0px -5%'});
d.querySelectorAll('.section,.card,.timeline-item,.media-item,.domain-card,.metric,.project-card').forEach(x=>{x.classList.add('reveal');if(!reduced)io.observe(x);else x.classList.add('in')});
const update=()=>{const max=d.documentElement.scrollHeight-innerHeight,p=max>0?scrollY/max:0;r.style.setProperty('--scroll',`${p*100}%`);progress.style.width=`${p*100}%`;if(nav)nav.classList.toggle('scrolled',scrollY>30)};addEventListener('scroll',update,{passive:true});update();
if(matchMedia('(pointer:fine)').matches){addEventListener('pointermove',e=>{r.style.setProperty('--mx',`${e.clientX}px`);r.style.setProperty('--my',`${e.clientY}px`);cursor.style.left=`${e.clientX}px`;cursor.style.top=`${e.clientY}px`;cursor.style.opacity='1'},{passive:true});d.querySelectorAll('a,button,summary').forEach(el=>{el.addEventListener('mouseenter',()=>b.classList.add('cursor-active'));el.addEventListener('mouseleave',()=>b.classList.remove('cursor-active'))})}
const hero=d.querySelector('.hero-home');if(hero&&!reduced){hero.addEventListener('pointermove',e=>{const q=hero.getBoundingClientRect(),x=(e.clientX-q.left)/q.width-.5,y=(e.clientY-q.top)/q.height-.5;const o=hero.querySelector('.hero-orbit'),a=hero.querySelector('.hero-aura');if(o)o.style.transform=`translate(${x*3}px,${y*2}px)`;if(a)a.style.transform=`translate(${x*-4}px,${y*-2}px) scale(1.01)`},{passive:true})}
d.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const el=d.querySelector(a.getAttribute('href'));if(el){e.preventDefault();el.scrollIntoView({behavior:reduced?'auto':'smooth',block:'start'})}}));
d.querySelectorAll('img').forEach((img,i)=>{if(!img.loading)img.loading=i<2?'eager':'lazy';img.decoding='async'});
const overlay=d.createElement('div');overlay.id='am-command';overlay.innerHTML='<div class="am-command-box" role="dialog" aria-modal="true" aria-label="Command Search"><input autocomplete="off" spellcheck="false" placeholder="Szukaj w MojeAlterego…" aria-label="Szukaj"><div class="am-results"></div></div>';b.appendChild(overlay);const input=overlay.querySelector('input'),results=overlay.querySelector('.am-results');
const entries=links.map(a=>({label:a.textContent.trim(),href:a.href})).filter(x=>x.label);const render=q=>{results.innerHTML='';const term=q.toLowerCase();entries.filter(x=>x.label.toLowerCase().includes(term)||x.href.toLowerCase().includes(term)).slice(0,14).forEach(x=>{const a=d.createElement('a');a.className='am-result';a.href=x.href;a.textContent=x.label||x.href;results.appendChild(a)})};
const openSearch=()=>{overlay.style.display='flex';input.value='';render('');input.focus()};const closeSearch=()=>{overlay.style.display='none'};addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openSearch()}if(e.key==='Escape')closeSearch()});input.addEventListener('input',()=>render(input.value));overlay.addEventListener('click',e=>{if(e.target===overlay)closeSearch()});
const ex=d.createElement('button');ex.className='am-experience-toggle';ex.type='button';ex.textContent='ENTER EXPERIENCE';ex.setAttribute('aria-pressed','false');ex.addEventListener('click',()=>{const on=b.classList.toggle('experience-mode');ex.textContent=on?'EXIT EXPERIENCE':'ENTER EXPERIENCE';ex.setAttribute('aria-pressed',String(on))});b.appendChild(ex);
const images=[...d.querySelectorAll('main img')];if(images.length){const viewer=d.createElement('div');viewer.className='am-viewer';viewer.innerHTML='<button type="button" aria-label="Zamknij">×</button><img alt=""><span class="am-counter"></span>';b.appendChild(viewer);const vi=viewer.querySelector('img'),counter=viewer.querySelector('.am-counter');images.forEach((img,i)=>img.addEventListener('click',()=>{vi.src=img.currentSrc||img.src;vi.alt=img.alt||'';counter.textContent=`${String(i+1).padStart(2,'0')} / ${String(images.length).padStart(2,'0')}`;viewer.classList.add('open')}));viewer.querySelector('button').addEventListener('click',()=>viewer.classList.remove('open'));viewer.addEventListener('click',e=>{if(e.target===viewer)viewer.classList.remove('open')})}
})();