import React from 'react'

const common = [
  ['O MNIE','/o-mnie.html'],['RELATIONSHIP','/relationship.html'],['FOTOGRAFIA','/fotografia.html'],['KSIĄŻKI','/ksiazki.html'],
  ['FILM','/zwiastuny.html'],['MASAŻE','/masaze.html'],['APLIKACJE','/aplikacje.html'],['AGENCI','/agenci.html'],['PROJEKTY','/projekty.html']
]

export function SiteHeader({onMenu}){return <header className="site-nav"><a href="/" className="brand"><img src="/assets/logo-master.svg" alt="Andrzej Mikulski — MojeAlterego"/></a><button className="menu-trigger" onClick={onMenu}>MENU <span>↗</span></button></header>}
export function InnerPage({number,kicker,title,intro,children,theme=''}){return <main className={`inner-page ${theme}`}><section className="inner-hero"><span className="page-number">{number}</span><div><span className="eyebrow">{kicker}</span><h1>{title}</h1>{intro&&<p>{intro}</p>}</div></section>{children}</main>}
export const Section=({number,title,children})=><section className="section"><div className="eyebrow">{number} / {title}</div>{children}</section>
export const Cards=({items})=><div className="route-cards">{items.map((x,i)=><article className="route-card" key={i}><span>{String(i+1).padStart(2,'0')}</span><h3>{x[0]}</h3><p>{x[1]}</p>{x[2]&&<a href={x[2]}>OTWÓRZ ↗</a>}</article>)}</div>

export function AboutPage(){return <InnerPage number="02" kicker="CZŁOWIEK · FOTOGRAF · FOTOREPORTER · AUTOR" title="O mnie." intro="Urodzony w Warszawie fotoreporter i autor książek, od 2023 roku mieszkający i tworzący na Śląsku. Łączę pracę górnika z działalnością fotoreporterską dla Agencji Fotograficznej REPORTER."><Section number="01" title="BIOGRAFIA"><div className="profile-grid"><figure><img src="/assets/andrzej-mikulski-about.png" alt="Andrzej Mikulski — fotograf, fotoreporter i autor"/><figcaption>ANDRZEJ MIKULSKI · FOTOGRAF · FOTOREPORTER · AUTOR · TWÓRCA</figcaption></figure><div className="prose"><h2>Obraz był pierwszy.<br/><em>Potem pojawiły się kolejne języki.</em></h2><p>Urodzony w Warszawie fotoreporter i autor książek, od 2023 roku mieszkający i tworzący na Śląsku. W swoim życiu zawodowym łączy pracę górnika z działalnością fotoreporterską dla Agencji Fotograficznej REPORTER.</p><p>Jego pasja do obrazu narodziła się już w dzieciństwie, a z czasem przerodziła się w dojrzałą twórczość, poszerzoną o zainteresowania filmem i informatyką.</p><p>Głównym obszarem jego eksploracji artystycznej jest fotografia dokumentująca życie codzienne oraz portret, choć pozostaje otwarty na różnorodne tematy i formy wyrazu.</p><p>Publikuje na łamach prasy codziennej, tygodników i miesięczników na całym świecie.</p><p>Założył i administruje grupą „Fotografia Uliczna”, która zrzesza obecnie ponad 75 tysięcy pasjonatów z całego globu. Pełni również funkcję jurora na portalu Flog.pl.</p><p>Jego dorobek obejmuje 16 wystaw indywidualnych oraz udział w ponad 300 wystawach zbiorowych, prezentowanych w ponad 40 krajach.</p><p>Został uhonorowany ponad 2000 nagród, wyróżnień i akceptacji w prestiżowych konkursach ogólnopolskich oraz międzynarodowych. Wybrane prace stanowią część zbiorów Artystycznego Dziedzictwa Międzynarodowej Federacji Sztuki Fotograficznej (FIAP).</p><p>W 2017 roku uzyskał tytuł Artysty Fotografa RP (AFRP). W 2019 roku AFIAP, a w 2020 roku EFIAP.</p><p>Jest autorem książek <em>Człowiek Roku</em>, tetralogii <em>CCR</em>, <em>Światło, które zostało</em>, <em>Baśń o Pornlandii</em>, <em>Cieszyn Noir</em>, <em>Ontologia Liczby i Geometrii</em> oraz komiksu <em>Druga połowa</em>.</p></div></div></Section><Section number="02" title="DROGA TWÓRCZA"><Cards items={[["Dzieciństwo","Początek fascynacji obrazem i obserwacją świata."],["Fotoreportaż","Rzeczywistość, codzienność, wydarzenia, ludzie i historie."],["Fotografia autorska","Dokument, portret, street photo i własny sposób opowiadania obrazem."],["Film i narracja","Rozszerzenie języka obrazu o ruch, montaż i formę audiowizualną."],["Literatura","Książki, światy alternatywne, refleksja i eksperyment narracyjny."],["Technologia","Informatyka, aplikacje, agenci AI i autorskie projekty cyfrowe."]]}/></Section></InnerPage>}

export function RelationshipPage(){return <InnerPage number="03" kicker="RELATIONSHIP COACHING · GLOBAL ONLINE" title="Relacja zaczyna się od Ciebie." intro="Konsultacje online na całym świecie. Spotkania mogą być prowadzone w ponad 100 językach — z wykorzystaniem tłumaczenia, gdy jest potrzebne. Bez gotowych recept. Bez oceniania. Z koncentracją na Twojej historii, komunikacji, granicach i decyzjach." theme="relationship-route"><Section number="01" title="METODA"><div className="prose narrow"><h2>Najpierw człowiek.<br/><em>Potem rozwiązanie.</em></h2><p>Nie szukam jednej uniwersalnej odpowiedzi. Najpierw poznaję człowieka, jego historię, sposób komunikowania, potrzeby, granice i rzeczywisty problem.</p><p>Celem nie jest decydowanie za Ciebie. Celem jest stworzenie przestrzeni, w której możesz lepiej zobaczyć możliwości, konsekwencje i własny wybór.</p></div><Cards items={[["Poznanie","Historia, kontekst, potrzeby i emocje bez pochopnych ocen."],["Zrozumienie","Mechanizmy pod powierzchnią konfliktu i powtarzające się schematy."],["Analiza","Wzorce zachowań, komunikacja, granice i reakcje."],["Strategia","Możliwości, decyzje, priorytety i kierunek działania."],["Praktyka","Przekładanie wniosków na konkretne rozmowy i zachowania."],["Transformacja","Świadoma zmiana i odpowiedzialność za własne wybory."]]}/></Section><Section number="02" title="OBSZARY PRACY"><Cards items={[["Człowiek","Potrzeby · wartości · granice · emocje · odpowiedzialność."],["Komunikacja","Słuchanie · konflikty · intencja · interpretacja · potrzeby."],["Relacja","Wzajemność · zaufanie · bliskość · dystans · zależność."],["Konflikt","Wyzwalacz · interpretacja · emocja · reakcja · konsekwencja."],["Granice","Wiem → mówię → konsekwentnie działam."],["Decyzja","Odbudować · uporządkować · zmienić · odejść · zacząć od nowa."]]}/></Section></InnerPage>}

export function BooksPage(){const books=[["CCR Tom I","Jak przetrwać w dziwnym świecie po przeniesieniu się do alternatywnej osi czasu.","https://www.empik.com/ccr-tom-i-jak-przetrwac-w-dziwnym-swiecie-po-przeniesieniu-sie-do-alternatywnej-osi-czasu-mikulski-andrzej,p1686064571,ebooki-i-mp3-p#ReviewsBox"],["CCR Tom II","Oś czasu w alternatywnych światach.","https://www.empik.com/ccr-tom-ii-os-czasu-w-alternatywnych-swiatach-mikulski-andrzej,p1687087904,ebooki-i-mp3-p"],["CCR Tom III","Ludzie Roku — oś 18 świadomości.","https://www.empik.com/ccr-tom-iii-ludzie-roku-os-18-swiadomosci-mikulski-andrzej,p1687088055,ebooki-i-mp3-p"],["Światło, które zostało","Autorska opowieść o tym, co pozostaje po czasie, doświadczeniach i ludziach, których spotykamy.","https://www.empik.com/swiatlo-ktore-zostalo-mikulski-andrzej,p1688662252,ebooki-i-mp3-p"],["Baśń o Pornlandii","Autorska narracja literacka z własnym światem i charakterystycznym spojrzeniem autora.","https://www.empik.com/basn-o-pornlandii-mikulski-andrzej,p1687292490,ebooki-i-mp3-p"],["Człowiek Roku","Literacki projekt autora związany z człowiekiem, jego wyborem i miejscem w świecie.","https://www.empik.com/czlowiek-roku-mikulski-andrzej,p1688657889,ebooki-i-mp3-p"],["Cieszyn Noir","Autorski projekt literacki osadzony w charakterze i atmosferze Cieszyna."],["Ontologia Liczby i Geometrii","Autorski projekt książkowy poświęcony ideom, strukturom i relacji pomiędzy liczbą a geometrią."],["Druga połowa","Autorski komiks i kolejna forma narracji w portfolio autora."]];return <InnerPage number="04" kicker="AUTOR · LITERATURA · ROZWÓJ · KOMIKS" title="Książki." intro="Historie, pytania i światy budowane słowem. Od literatury fantastycznej i alternatywnych rzeczywistości po książki o relacjach, decyzjach i świadomym życiu."><Section number="01" title="BIBLIOTEKA"><Cards items={books}/></Section><Section number="02" title="ZAPOWIEDŹ"><article className="prose book-preview"><h2>Nie czytaj tej książki, jeśli nie chcesz niczego zmieniać.</h2><p>Są książki, które czytasz i odkładasz na półkę.</p><p>Są też takie, które sprawiają, że po przeczytaniu jednej strony zaczynasz inaczej patrzeć na siebie, swoje relacje, decyzje i życie.</p><p>Ta książka należy do tej drugiej kategorii.</p><p><strong>O miłości. O granicach. O strachu. O czasie. O własnej wartości. O błędach. O przebaczeniu. O marzeniach. O odwadze.</strong></p><p>Nie pytaj wyłącznie: „Czy to prawda?” <strong>Zapytaj: „Czy to dotyczy mnie?”</strong></p><p><strong>ZROZUMIENIE → DECYZJA → DZIAŁANIE → ZMIANA</strong></p></article></Section></InnerPage>}
